### ISSUE TITLE
Tests?

### ISSUE THREAD

**Issue by natefinch** [xo/xo#129]
I hope I'm wrong and just missing something obvious... but are there no tests?

**Comment by natefinch** [comment]
Are you guys open to having some help?  I like the code that is generated - how simple it is.  But I would want a ton of tests to make sure I'm not breaking things. I'm happy to pitch in and write tests, if you don't mind a little tweaking to make things more testable, if necessary.

**Comment by turnkey-commerce** [comment]
That would be very helpful, I think Ken does run some integration tests on commits but would be great to have some automatic tests.  I'm somewhat new to this project and don't have commit rights but I'm sure Ken would support that.  What say ye Ken?

**Comment by kenshaw** [comment]
Yes, I do run tests, mainly the "examples" tests. The issue with the way `xo` runs, which is that it generates code, it is pretty cumbersome to write a test for the actual generated code, while the Go compiler itself basically tests whether or not the generated code is at least syntactically correct. My idea for `xo` has always been that it simply and rapidly generates the short wrappers around what is otherwise raw SQL code. I understand that this is not 100% ideal, originally I had written `xo` for PostgreSQL with a very specific schema, and then realized that the same generation being done for PostgreSQL would be equally useful for MySQL, SQL Server, etc.

`xo` is really due for a complete top-to-bottom overhaul; including writing things like unit tests. At the moment, I just don't have the time to really commit to that.

**Comment by natefinch** [comment]
Ahh, tests in the examples. I didn't think to look there. If you could write something up like a contributing doc, I'd be happy to put some work into this tool.  It really does fit exactly what I think is the best way to do persistence to a relational db in Go.  

I'd be more than happy to also schedule a video chat or something if that's easier. I know you're on the other side of the world but I can be flexible.

**Comment by natefinch** [comment]
@kenshaw I understand you don't have the time to commit to making a big overhaul, but maybe the fix is to let other people work on an overhaul? Or at least work on getting PRs vetted and merged.

Would you consider either adding contributors to the project or even moving it to a github organization?  I'm actively using this at Mattel, as well as having a personal interest in this approach as the correct approach - I even submitted a talk about it to GothamGo just yesterday :)

**Comment by turnkey-commerce** [comment]
I second the request by Nate as I have a PR for composite primary keys that's been awaiting approval for a couple of months and will soon open a PR for Cockroach DB support.

**Comment by natefinch** [comment]
I made a fork of the project here:  github.com/xoxo-go/xoxo  
It's identical to the current xo binary except with a different name, obviously.  The only difference is that the generated code will say generated by xoxo instead of generated by xo.

I don't want to hijack the project, but I do want to keep it under development.  I don't want to be the sole maintainer, my hope is that we'll get multiple active users together to help maintain it.  I'd love to talk to anyone else who is interested in actively maintaining this project.

**Comment by jmhodges** [comment]
Generating the postgres booktest example, for instance, will not build because `models.BooksByTitleYear` is now `models.BooksByTitle`.

Hm, I think I'll try fixing this as I go along, but it'll be a bit of a hairball.

**Comment by kenshaw** [comment]
@jmhodges please join us in #xo on gophers.slack.com -- we can discuss further there. Not sure why the `booktest` here with your version of PostgreSQL was't coming out as `BooksByTitleYear` -- I just reran it, and I did not encounter the same behavior.

**Comment by jmhodges** [comment]
This turned out to be because the index names auto-generated by postgresql 9.5 are not the same as 9.6 and the booktest example was built for use again 9.6
