### ISSUE TITLE
Import path broken: github.com/knq/xo

### ISSUE THREAD

**Issue by tmichaud314** [xo/xo#152]
This project's github organization changed from 'knq' to 'xo'. However .go imports still reference the old organization.

**Comment by jvsteiner** [comment]
perhaps related, I am getting `main.go:20:2: use of internal package not allowed`

**Comment by natefinch** [comment]
If this is blocking you, you can git clone xo/xo into knq/xo inside your GOPATH and then everything will work correctly.  After you git clone, do a go get, and it'll get the dependencies, but since the xo code exists it won't redownload that. 

Go get is the only part of the go tooling that knows about git URLs, so everything else will just work as long as the code on disk is where the import path expects it to be.

**Comment by jvsteiner** [comment]
Thanks Nate, got it working by using:
```
go get -u github.com/xo/usql
go get -u github.com/knq/xo
```

**Comment by natefinch** [comment]
Yeah, GitHub will redirect the old url, so that will work until the imports
in the code are changed to xo/xo

**Comment by jvsteiner** [comment]
understood, and thanks.
