### ISSUE TITLE
No All Query?

### ISSUE THREAD

**Issue by cschep** [xo/xo#190]
Hi! 

Thank you for xo! I’m just getting started and I noticed right away that there is no way to select all of a certain type out of the box. Is this the correct behavior? Should I just add it as custom template?

Any reason it’s not there? Seems useful.

Thanks!

**Comment by kenshaw** [comment]
Why would you ever select every row from a table? I realize that people want to do this, but I've never actually seen a vanilla use of "return every single result in this table" for any real software. If the table is small enough to fit into memory, use static data. Otherwise, the number of rows is probably going to be prohibitive, and you need to use a `LIMIT` clause or some such. That would fall under a "custom query" in my opinion.

**Comment by cschep** [comment]
Hmm absolutely that is true. I guess people probably ask because they just start hacking around on a trivial app and want to just see the output. That's at least what I'm doing :) 

Maybe a default query for pagination/limit. But at the end of the day I suppose you're right that will be app specific enough to just use a custom template for.

Thanks for the quick response and thanks again for `xo` !

**Comment by kenshaw** [comment]
It would be impossible without human intervention to automatically determine which fields to use for pagination. That's the entire point of custom templates: if your schema is designed around a specific standard / style (ie, every table has a "`id INTEGER`" field), then it would be trivial to add standardized pagination to the schema in use by your organization.

The lack of a `*All` query was intentional. While it might make sense to automatically do that for `int` based fields, most other key types do not have any logical or immediately apparent pagination scheme. Without getting into philosophical arguments about "what is the 'right' schema?" (answer: there is none), I do not know of any way this can be generalized, to, for example, `STRING` or `UUID` or `OID` primary key fields. My advice would be to eschew using `INTEGER`s as keys, and instead move to unique strings / UUIDs or some other type suited to the specific schema design in question. This goes for things such as link tables or other "meta" tables that are associated primarily to other tables. Large database-based software almost always will require a unique identifier per row, for management purposes, and these should be included wherever possible.

For what it's worth, most of the "very large" databases that I see in the wild use some kind of custom `VIEW` or other partitioning scheme, coupled with highly tuned indexes and queries to accomplish pagination.
