### ISSUE TITLE
help with one to many query?

### ISSUE THREAD

**Issue by cschep** [xo/xo#193]
Hey, thanks again for XO.

I'm struggling with a one to many relationship and I was hoping for some guidance.

I have the following tables with a foreign key relationship. If i have a Projection then I can get the player, as is the default template, but I'm curious how I could end up with something like this (I think it's a foreign key inverse?):

```
func (p *Player) Projections(db *sql.DB) ([]*Projections, err) {
    ...
}
```
I've tried customizing the foreignkey template but I feel like I'm in the wrong spot, Is there a way for a type to know what's relating to IT instead? For instance in the Players template knowing that Projections is pointing to it? That's tricky.

Also if that's not the right way to do it I imagine I could write a custom query to do this no problem but.. It would want to return another custom struct like []*ProjectionResult..

.. can you write a custom query to return an already generated type like []*Projection ?

edit: I'd even be happy to just be able to add the function myself to the Projection type, but how do you add such a specific thing like ProjectionsBySteamerID, without adding it to every template? Again a custom template works fine but how do you just return the Projection type I've already generated instead of a mirrored ProjectionResults type with all the same fields?

Thanks for any guidance!

```
CREATE TABLE players (
    id INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT,
    steamer_id INTEGER UNIQUE,
    name TEXT NOT NULL DEFAULT '',
);

CREATE TABLE projections (
    id INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT,
    steamer_id INTEGER  REFERENCES players(steamer_id),
    year INTEGER NOT NULL,
    name TEXT NOT NULL,
    handed TEXT,
    is_batter INTEGER,
    ... lots of stats omitted for brevity ...
);
```

**Comment by bir** [comment]
The issue is you do not have an index on projections for steamer_id.
`CREATE INDEX idx_projections_steamer_id
ON projections (steamer_id);`

XO will see this and generate code like:
`// ProjectionsByPlayerID retrieves a row from 'public.projections' as a Projection.
//
// Generated from index 'idx_projections_steamer_id'.
func ProjectionsBySteamerID(db XODB, steamerID sql.NullInt64) ([]*Projection, error) {...`

Note, this is an accessory method, not directly attached to the Players object.  Use it like:
`pp, err := ProjectionsBySteamerID(db, myPlayer.steamerID)`

Unrelated, any reason not to use projection.player_id = player.id as the FK instead of the surrogate?

**Comment by cschep** [comment]
Wow this took me too long to respond. Thanks this is exactly what I needed!

I did write a custom template to make these helper methods get generated.. but I basically had just copied the `index` template over and then used the steamer_id on the player. This is much cleaner.

Thanks again!
