### ISSUE TITLE
Add support for pgx postgres driver

### ISSUE THREAD

**Issue by ninedraft** [xo/xo#222]
[pgx](https://github.com/jackc/pgx) has a much better support for prepared statements and custom postgres types. It's the only stopper for me to use `xo` in many projects.

**Comment by kenshaw** [comment]
@ninedraft -- `xo` only generates model code for you. `xo` does not open or make connections to the database in whatever code uses the generated models -- as such it's 100% entirely possible to use `pgx` with code generated by `xo`  for a PostgreSQL database. 

In fact, I've tested `pgx` with `xo` generated code previously. If you're referring to using direct API calls that `pgx` provides (that is to say, circumventing the standard Go `database/sql` package) then you would need to create your own custom `xo` templates. Since that would _not_ be portable to the other database drivers (MySQL, Microsoft SQL Server, Oracle, SQLite3), I have not tried to do that. Please note it is fairly simple to modify the default `xo` templates in order to accommodate different databases.
