### ISSUE TITLE
Tool to generate gRPC Server from xo

### ISSUE THREAD

**Issue by walterwanderley** [xo/xo#243]
I've just develop a little tool to generate boilerplate code of a gRPC Server from xo.

https://github.com/walterwanderley/xo-grpc

May i get some feedback from xo users?

**Comment by kenshaw** [comment]
@walterwanderley Thanks, I'll take a look at this. I had been working on a complete overhaul and modernization of the xo codebase during my spare time over the last month or so. Part of the overhaul's amibitions/goals is to support multiple template types, which is completed. I am now working on templates for: REST server (generates something like PostgREST for any database schema), GraphQL server generation, Graphviz diagram generation, and a gRPC server generation. 

Additionally, I plan on supporting/generating similar packages for other programming languages, where viable -- for example, PHP, Java, Python, others. 

I realize some of this may clash with your work. I deeply apologize as this has been happening in parallel, and instead of announcing my work I simply wanted to wait until an alpha quality of the new `xo` overhaul was completed. 

I'm ecstatic to announce that that time is now. I just pushed the alpha level quality `xo`. Please have a look. 

Your feedback would be greatly appreciated. Over the next week or two, I'll complete the other template types, and push. Hopefully we can incorporate your work on gRPC directly.

Cheers, and thanks again for your contribution!

**Comment by walterwanderley** [comment]
Great news! The new features seems incredible! I will take a look at this work.

Thanks!
