### ISSUE TITLE
SQLEXPRESS/db: Unable to get instances from Sql Server Browser on host localhost

### ISSUE THREAD

**Issue by suntong** [xo/xo#303]
When I tried 

`xo schema mssql://user:pass@localhost/SQLEXPRESS/dbname -o mssqlmodels`

I got 

`error: unable to get instances from Sql Server Browser on host localhost: read udp [::1]:64426->[::1]:1434: i/o timeout`

I tried with my real hostname and get the same timeout as well. 

`error: unable to get instances from Sql Server Browser on host xx: read udp 192.168.0.nnn:53343->192.168.0.nnn:1434: i/o timeout`

How to work on SQLEXPRESS/db? thx

**Comment by kenshaw** [comment]
Please try `xo schema mssql://user:pass@localhost/SQLEXPRESS`.

**Comment by suntong** [comment]
hmm.. @kenshaw, I might not have expressed clearly. 

I was following the format of 

`mssql://user:pass@remote-host.com/instance/dbname`

Note the "**/instance**" part after the "remote-host.com".

basically with the database connection URLs in the form of  
`sqlserver://user:pass@remote-host.com/dbname`

- My `remote-host.com` is in the form of `my-host\SQLEXPRESS`. 
- The `SQLEXPRESS` is the _**instance**_ name.
- The `dbname` is within such SQLEXPRESS/db. 

Would url encode the "`\`" character be the solution?

**Comment by kenshaw** [comment]
I'm assuming you're on a Windows domain? Please consult the underlying Go SQL Server driver for the connection options. If it is `instance` and `dbname`, then yes, you'd use the path component of the URL. There might be other requirements, however, to use Windows domain authentication if that's what you're attempting to do.

**Comment by suntong** [comment]
Yes, it is `instance` and `dbname`:

![image](https://user-images.githubusercontent.com/422244/128403212-5b87193d-fd42-4cdc-8484-d209c356c6b3.png)

and yes, I've just  confirmed that using the path component of the URL is NOT working:

![image](https://user-images.githubusercontent.com/422244/128403660-8008a5ba-5466-4ab6-9210-8db3f8c487cd.png)

**Comment by kenshaw** [comment]
Unfortunately, I don't have a Windows environment to test this against. `usql` has been developed almost exclusively against Microsoft's published Docker container image. If you're able to, please try to build / open a connection in Go using the [`github.com/denisenkom/go-mssqldb`](https://github.com/denisenkom/go-mssqldb) driver and share with me the DSN string you're able to connect with and what you expect the equivalent `xo` URL would be (please note that `xo` and `usql` use the `dburl` package for connecting to databases). I'll check/verify that the generated DSN works as expected.

For reference, currently when given a string of this:

```
mssql://user:!234%23$@localhost:1580/dbname
```

`dburl` produces the following connection string:

```
Database=dbname;Password=!234#$;Port=1580;Server=localhost;User ID=user
```

This would appear to be correct to me, but since I am unable to test against your specific environment, I am only able to postulate on whether or not it would work correctly.

**Comment by suntong** [comment]
Thanks for the detailed reply @kenshaw. 

You might be replying to my original email, but since then, my above content has evolved from "Problem! 😱" to "Hold on ... 😊" to "Solved! ✌️". 

Everything is now working (and the problem has been at my SQL Server side). 
Thanks again for the above detailed insight, it gives me a better understanding of what's going on beneath the hood, and will surely help the next person in need. 

Thanks!

**Comment by kenshaw** [comment]
@suntong Yes, I was replying to the comment that I believe you deleted. In the future it'd be great if you didn't delete comments, as a reference for others who may be encountering the same problem. Can you share what the syntax for the URL you ended up using was? Thanks.

**Comment by suntong** [comment]
Here it is, 

![image](https://user-images.githubusercontent.com/422244/128403660-8008a5ba-5466-4ab6-9210-8db3f8c487cd.png)

It wasn't working before, but now it is.
