### ISSUE TITLE
Recommendation for version/commit to use

### ISSUE THREAD

**Issue by fho** [xo/xo#307]
Hello,

we are currently using a very old xo version and I want to update to a more recent one, especially to be able to use the context-ware db methods.
I tried HEAD (380481f558498aa83540245f9873965cc568a432) from master but with that version some of our templates break because some templates functions were commented out in commit https://github.com/xo/xo/commit/3b4f0c04f434487fc7a2db6813186815ad1528b0  ([funcs.go](https://github.com/xo/xo/blob/380481f558498aa83540245f9873965cc568a432/templates/gotpl/funcs.go#L149)).

Could you recommend a specific commit that you think is stable and could be used in production environments?
Even better would be to have a git-tag for it. :-)

thanks in advance!

**Comment by hhhapz** [comment]
Hey @fho. XO has been completely rewritten from scratch.

Due to the nature of the changes, and the complete refactoring of the SQL generation templates, the old methods are no longer used (and will not be provided anymore). This is a breaking change however was required as the old template functions were very difficult to manage/maintain. The current master commit is usable, however the functions will no longer be :(. 

Tagged version will most likely come soon, I have been busy with my own school work and have not had the opportunity to fix up a few things and write more documentation before I feel that xo will be ready for a release (however perhaps a v0.1 tag may be appropriate. Let us know if the new template functions are difficult to use or lack some functionality.

The new templates are available in templates/gotpl/{query,schema}, and are generalised for each kind of operation and are consolidated for all 5 databases.

**Comment by fho** [comment]
@hhhapz thanks a lot for the lightning fast response and for providing the amazing xo pkg. :-)
I'll try to rewrite our templates to use the new functions then. I first thought they were commented out only temporarily.
If it should not work out, I'll create a new issue about it.
