### ISSUE TITLE
README: fieldnames template function is mentioned in example but it does not exist anymore

### ISSUE THREAD

**Issue by fho** [xo/xo#309]
In https://github.com/xo/xo#example-custom-template----adding-a-getmostrecent-lookup-for-all-tables-go 
there is a line
```
        if err := rows.Scan({{ fieldnames $type.Fields (print "&" $short) }}); err != nil {
```
the fieldnames template function is commented out and can't be used though.

**Comment by hhhapz** [comment]
From a recent discussion with kenshaw, I have realised that the extensibility of the templates is severely lacking now (making it impossible to write custom queries cleanly). It is in the road map to fix this. Most likely, all queries will be defined in a new template file using `define` directives, allowing users to define more templates, and modify the already existing ones, instead of the current, rigid method via go template functions that just prebake it disallow any level of configurability. 

I had thought of implementing something similar earlier, however with the lack of foresight I did not realise this would break configurability, and will try to reimplement something similar to this (however, using `{{ define }}`s, and one for each driver individually to clean things out more :))

**Comment by fho** [comment]
@hhhapz thanks for the info, I'm struggling since hours with converting our old templates to the new version. 
It's difficult for me so far to understand which template function does what, which template var contains what kind of data and how to combine it to get the wanted result.

**Comment by hhhapz** [comment]
The types that is executed for each template is found in templates/gotpl/types.go, and the functions are in funcs.go, and I can agree there is a seperate refactor in need. This will be done eventually. I plan to reintroduce more functions that reintroduce the flexibility of the old template functions, such as being able to get the columns comma-seperated, the number of args using `nthparam`, etc.

**Comment by hhhapz** [comment]
Just out of curiosity, can you send your modifications to the old template? would be good to keep in mind :)

**Comment by fho** [comment]
Yes, I think I can send an example when I have something working.
So far nothing works :-)

**Comment by hhhapz** [comment]
I meant your old template

**Comment by switchupcb** [comment]
What can we do for this functionality? Is there a way to use a custom `func.go` we can provide our own functions with?

**Comment by switchupcb** [comment]
This can be fixed by using the solution to #313

**Comment by kenshaw** [comment]
Couple of things -- as per @switchupcb said, #313 provides a temporary interim solution. Separately, all of the current Go logic on these functions will be migrated over to the new `funcs.go.tpl` functionality. I'm almost done with the changes for that but have some minor issues that need to be worked out. Should have this done by the end of the day.

**Comment by kenshaw** [comment]
I just completed switching all template funcs over to the custom funcs. All templates should now be fully configurable/editable, including most of the Go logic involved.

**Comment by nrolans** [comment]
I found myself in a similar situation adapting templates. Would it be possible to have a loose notion of version or even just some vague tags? Templates have changed a lot since "v1". Around once a month since the v2 rewrite started, I have a look at new commits and test/update my templates. This takes a while, then more changes come. My concern is that there might be an important fix in the future and I'll need to update my templates again to benefit from it.

I understand many are spending their free time to this great opensource project and I don't mean to be ungrateful or overly demanding. I hope we can find a solution that's not too honerous. Thanks for all the work on this!

**Comment by kenshaw** [comment]
@nrolans I apologize for the "chatter" in the changing templates. I had expected this to happen over the course of the rewrite/modernization of the code base and is why I have yet to tag a v2 release. Now that the templates are fully done through dynamic means, I expect the templates will become more stable.

**Comment by kenshaw** [comment]
@nrolans I've added some of the legacy functions in to the Go templates. These need to be enabled via the `--go-legacy` option. I would not recommend using them, and would instead suggest migrating to the new templates.
