### ISSUE TITLE
Is there a way to use our own func.go?

### ISSUE THREAD

**Issue by switchupcb** [xo/xo#313]
The current `func.go` has many implementation-specific features which makes creating an initial template hard for the user. This means they must edit the template directly or edit the package in `GOROOT` which is not consistent.

**Comment by hhhapz** [comment]
Currently there is no way to do this other than forking xo. It is planned to add more convenience methods so that the templates are more powerful in general.

**Comment by kenshaw** [comment]
@switchupcb I just pushed a change that will allow you to define a `funcs.go.tpl` file in the root of any of the templates. Within it, you can define code that will be interpreted by Yaegi ([see here](https://github.com/traefik/yaegi). There is a sample `funcs.go.tpl` that is generated with the `xo dump` command for the Go template that shows an example. Any returned func in the `template.FuncMap` from the `funcs.Init` call will be added (or will override) to the set of funcs that are otherwise passed to the templates.
