### ISSUE TITLE
Unable to run because of createdb error

### ISSUE THREAD

**Issue by ayo-ajayi** [xo/xo#367]
Here is the error message->
error: createdb: unable to import package: 1:22: import "createdb" error: unable to find source related to: "createdb"

**Comment by Fulululu** [comment]
try to use an old version of `xo`. I build it from source by using script file named `build-release.sh`, then it works.
(commit 42b11c7, go version go1.18.2 darwin/amd64)

**Comment by evassilyev** [comment]
The suggestion of @Fulululu works. I've succesfully tested it on commit: [634ad55c92dc3eb4f79b3146dbeef0553d0b03d7](https://github.com/xo/xo/commit/634ad55c92dc3eb4f79b3146dbeef0553d0b03d7)
The problem is in the commit [4a3887872734d5720137731ec7ca439bfed0543a](https://github.com/xo/xo/commit/4a3887872734d5720137731ec7ca439bfed0543a)

**Comment by evassilyev** [comment]
According to the changes in commit [4a3887872734d5720137731ec7ca439bfed0543a](https://github.com/xo/xo/commit/4a3887872734d5720137731ec7ca439bfed0543a) **xo** required go version 1.19+
With go 1.19+ **xo** works properly.
I recommend to contributors to update README.md with the new requirement of use go 1.19+.

**Comment by ayo-ajayi** [comment]
Alright, thank you @Fulululu @evassilyev
